In [7]:
import numpy as np

In [ ]:
# FONTOS!!!
# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!

array([2, 2])

In [33]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tupel-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

def create_array(size = (2,2)) -> np.array:
    return np.zeros(size, dtype=int)

array([[0, 0],
       [0, 0]])

In [17]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlót feltölti egyesekkel

#Be: [[1,2],
#     [3,4]]

#Ki: [[1,2],
#     [3,1]]

#set_one()

def set_one(l) -> np.array:
    np.fill_diagonal(l, 1)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [31]:
# Transzponáld a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 2], [3, 4]]
# do_transpose()

def do_transpose(m) -> np.array:
    return np.transpose(m)

[[7 4 2 4]
 [6 2 2 1]
 [6 0 0 1]
 [1 1 5 7]]
[[7 6 6 1]
 [4 2 0 1]
 [2 2 0 5]
 [4 1 1 7]]


In [47]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, alapértelmezetten 
# Be: [0.1223, 0.1675], n = 2
# Ki: [0.12, 0.17]
# round_array()

def round_array(arr, n = 2) -> np.array:
    return np.round(arr, n)

[0.56375132 0.73766965 0.91851982]
[0.564 0.738 0.919]


In [49]:
# Készíts egy olyan függvényt, ami a bementként  0 és 1 ből álló tömben a 0 - False-ra az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

def bool_array(l: np.array) -> np.array:
    return l == 1

[[ True False False]
 [ True  True  True]
 [False False False]]


In [50]:
# Készíts egy olyan függvényt, ami a bementként  0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# invert_bool_array()

def invert_bool_array(l: np.array) -> np.array:
    return l == 0

In [51]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()

def flatten(l: np.array) -> np.array:
    return l.flatten()

[1 2 3 4]
